spring:
  application:
    name: api-gateway
server:
  port: 8888
  tomcat:
    protocol_header: x-forwarded-proto
  use-forward-headers: true
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false
eureka:
  client:
    healthcheck:
      enabled: true
#    registerWithEureka: true
#    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
zuul:
  sensitiveHeaders: Authetication
  routes:
    auth: #authetication service
      path: /auth/**
      serviceId: auth-service
      strip-prefix: false
      #url: http://localhost:9000
ribbon:
  eureka:
    enabled: true
application:
  authServiceUrl: http://auth-service/auth/v1/me
